### ISSUE TITLE
Background - 3 lanes

### ISSUE THREAD

**Issue by milluzzi** [milluzzi/KSU_SoftwareEngineering_Gamma#24]
Add some kind of background with three lanes for the arrows to go down.

**Comment by milluzzi** [comment]
Just thought of something: When the background is rendered, depending on how it's done, it may insert values into the depth buffer, causing other rendered items to not show up.

This would be easily fixed by disabling depth testing. We don't currently need it.

There's an example of how to do it here:
https://editor.p5js.org/cacheflowe/sketches/SW763JUky

The magic line of code is:
setAttributes('depth', true);

**Comment by WolfWindOW** [comment]
Added in PR #32. Additional testing may be needed, see above
